### ISSUE TITLE
Improve watch command

### ISSUE THREAD

**Issue by ihebattia** [ihebattia/migrate_extra#1]
## Description
> As a developer, I want to use a cross-platform file change monitor instead of resource watcher symfony library.

## Acceptance criteria
- [ ] A cross-platform file change monitor is used.
  - [ ] No more infinite loop "while (true)".
  - [ ] No more sleep() function.

## Subtasks
- [ ] Update drush migrate-debug-watch to use either PHP Inotify or fswatch.
- [ ] Update drush migrate-debug-watch command help.
- [ ] Update README.md documentation.
- [ ] Commit and push
  
## Helpful links
- http://php.net/inotify-init
- https://www.simplicity.be/article/watching-files-and-directories-php/
- http://emcrisostomo.github.io/fswatch/getting.html
- https://github.com/emcrisostomo/fswatch#features
